/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BambooParallax: typeof import('./src/components/effects/BambooParallax.vue')['default']
    BlogCard: typeof import('./src/components/BlogCard.vue')['default']
    BlogList: typeof import('./src/components/BlogList.vue')['default']
    BlossomCanvas: typeof import('./src/components/effects/BlossomCanvas.vue')['default']
    Comment: typeof import('./src/components/Comment.vue')['default']
    CommentItem: typeof import('./src/components/CommentItem.vue')['default']
    CommentList: typeof import('./src/components/CommentList.vue')['default']
    DockBar: typeof import('./src/components/WarmOS/DockBar.vue')['default']
    ElAvatar: typeof import('element-plus/es')['ElAvatar']
    Error: typeof import('./src/components/Error.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    LiquidGlass: typeof import('./src/components/LiquidGlass.vue')['default']
    LoadingOverlay: typeof import('./src/components/LoadingOverlay.vue')['default']
    MarkdownEditor: typeof import('./src/components/MarkdownEditor.vue')['default']
    MouseTrail: typeof import('./src/components/effects/MouseTrail.vue')['default']
    RainCanvas: typeof import('./src/components/effects/RainCanvas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SunriseParallax: typeof import('./src/components/effects/SunriseParallax.vue')['default']
    SystemPanel: typeof import('./src/components/WarmOS/SystemPanel.vue')['default']
  }
}
