repos:
  # isort for sorting Python imports
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        args: ["--profile", "black"] # 使用 black 风格的排序

  # Ruff for Python linting and formatting
  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.287
    hooks:
      - id: ruff
        args: ["--fix"] # 自动修复格式问题

  # Prettier for Vue and other frontend files
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: ["--config-precedence", "prefer-file"]
        files: "\\.(vue|js|jsx|ts|tsx|css|scss|html|json|yaml|yml|md)$"
        language_version: default # 使用默认的 Node.js 环境
