/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Read Root */
    get: operations["read_root__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/blog/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Blogs */
    get: operations["get_blogs_apis_v1_blog__get"];
    put?: never;
    /** Create Blog */
    post: operations["create_blog_apis_v1_blog__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/blog/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Blog */
    get: operations["get_blog_apis_v1_blog__id__get"];
    /** Update Blog */
    put: operations["update_blog_apis_v1_blog__id__put"];
    post?: never;
    /** Delete Blog */
    delete: operations["delete_blog_apis_v1_blog__id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/blog/{id}/like": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Like Status */
    get: operations["get_like_status_apis_v1_blog__id__like_get"];
    put?: never;
    /** Toggle Like */
    post: operations["toggle_like_apis_v1_blog__id__like_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/auth/register": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Register User */
    post: operations["register_user_apis_v1_auth_register_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/auth/verify/{token}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Verify Email
     * @description 根据token对邮箱进行验证
     */
    get: operations["verify_email_apis_v1_auth_verify__token__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/auth/login": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Login */
    post: operations["login_apis_v1_auth_login_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/auth/forgot-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Forgot Password
     * @description 发送密码重置邮件
     */
    post: operations["forgot_password_apis_v1_auth_forgot_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/auth/reset-password": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Reset Password
     * @description 使用令牌重置密码
     */
    post: operations["reset_password_apis_v1_auth_reset_password_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/auth/refresh": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Refresh Token
     * @description 刷新访问令牌
     */
    post: operations["refresh_token_apis_v1_auth_refresh_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/img_bed/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Image Upload
     * @description Upload an image file. Returns the public URL.
     *
     *     The file is stored via StorageService (MinIO or local filesystem).
     */
    post: operations["image_upload_apis_v1_img_bed__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/img_bed/{object_name}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Image Get
     * @description Get an image file by its hash-based filename.
     */
    get: operations["image_get_apis_v1_img_bed__object_name__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/permission/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Permission */
    get: operations["get_permission_apis_v1_permission__get"];
    put?: never;
    /** Have Permission */
    post: operations["have_permission_apis_v1_permission__post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/user/info": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Info */
    get: operations["get_user_info_apis_v1_user_info_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/user/info/{user_uuid}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get User Info By Id */
    get: operations["get_user_info_by_id_apis_v1_user_info__user_uuid__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/user/edit": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Edit User Info */
    post: operations["edit_user_info_apis_v1_user_edit_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/comment/create": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** Create Comment */
    post: operations["create_comment_apis_v1_comment_create_post"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/comment/get/{blog_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Comments */
    get: operations["get_comments_apis_v1_comment_get__blog_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/comment/get/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Get Comment */
    get: operations["get_comment_apis_v1_comment_get__comment_id__get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/comment/delete/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /** Delete Comment */
    delete: operations["delete_comment_apis_v1_comment_delete__comment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/comment/update/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /** Update Comment */
    put: operations["update_comment_apis_v1_comment_update__comment_id__put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/stats": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Stats
     * @description 获取仪表盘统计数据
     */
    get: operations["get_stats_apis_v1_admin_stats_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/users": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Users
     * @description 获取用户列表
     */
    get: operations["get_users_apis_v1_admin_users_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/users/{user_id}/role": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Update User Roles
     * @description 更新用户角色
     */
    put: operations["update_user_roles_apis_v1_admin_users__user_id__role_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/users/{user_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete User
     * @description 删除用户
     */
    delete: operations["delete_user_apis_v1_admin_users__user_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/blogs": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Blogs
     * @description 获取文章列表(包含未发布的)
     */
    get: operations["get_blogs_apis_v1_admin_blogs_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/blogs/{blog_id}/publish": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    /**
     * Toggle Blog Publish
     * @description 切换文章发布状态
     */
    put: operations["toggle_blog_publish_apis_v1_admin_blogs__blog_id__publish_put"];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/blogs/{blog_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Blog
     * @description 删除文章
     */
    delete: operations["delete_blog_apis_v1_admin_blogs__blog_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/comments": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Comments
     * @description 获取评论列表
     */
    get: operations["get_comments_apis_v1_admin_comments_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/comments/{comment_id}": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete Comment
     * @description 删除评论
     */
    delete: operations["delete_comment_apis_v1_admin_comments__comment_id__delete"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/apis/v1/admin/roles": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get Roles
     * @description 获取所有角色
     */
    get: operations["get_roles_apis_v1_admin_roles_get"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    /** AdminBlogListResponse */
    AdminBlogListResponse: {
      /** Items */
      items: components["schemas"]["AdminBlogResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
    };
    /** AdminBlogResponse */
    AdminBlogResponse: {
      /** Id */
      id: number;
      /** User Uuid */
      user_uuid: string;
      /** Username */
      username: string;
      /** Title */
      title: string;
      /** Cover Url */
      cover_url: string | null;
      /** Tags Name */
      tags_name: string[];
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
      /** View Count */
      view_count: number;
      /** Likes Count */
      likes_count: number;
      /** Published */
      published: boolean;
    };
    /** AdminCommentListResponse */
    AdminCommentListResponse: {
      /** Items */
      items: components["schemas"]["AdminCommentResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
    };
    /** AdminCommentResponse */
    AdminCommentResponse: {
      /** Id */
      id: number;
      /** Blog Id */
      blog_id: number;
      /** Blog Title */
      blog_title: string;
      /** User Id */
      user_id: number;
      /** Username */
      username: string;
      /** Content */
      content: string;
      /** Created At */
      created_at: number;
      /** Updated At */
      updated_at: number;
    };
    /** AdminRoleResponse */
    AdminRoleResponse: {
      /** Id */
      id: number;
      /** Name */
      name: string;
      /** Description */
      description: string | null;
      /** Is Default */
      is_default: boolean;
      /**
       * Permissions
       * @default []
       */
      permissions: string[];
    };
    /** AdminStatsResponse */
    AdminStatsResponse: {
      /** Total Users */
      total_users: number;
      /** Total Blogs */
      total_blogs: number;
      /** Total Comments */
      total_comments: number;
      /** Total Blogs Today */
      total_blogs_today: number;
      /** Total Comments Today */
      total_comments_today: number;
      /**
       * Recent Blogs
       * @default []
       */
      recent_blogs: components["schemas"]["AdminBlogResponse"][];
      /**
       * Recent Comments
       * @default []
       */
      recent_comments: components["schemas"]["AdminCommentResponse"][];
    };
    /** AdminUserListResponse */
    AdminUserListResponse: {
      /** Items */
      items: components["schemas"]["AdminUserResponse"][];
      /** Total */
      total: number;
      /** Page */
      page: number;
      /** Page Size */
      page_size: number;
      /** Total Pages */
      total_pages: number;
    };
    /** AdminUserResponse */
    AdminUserResponse: {
      /** Id */
      id: number;
      /** Uuid */
      uuid: string;
      /** Username */
      username: string;
      /** Email */
      email: string;
      /** Is Verified */
      is_verified: boolean;
      /** Created At */
      created_at: number;
      /**
       * Roles
       * @default []
       */
      roles: string[];
    };
    /** BlogCreate */
    BlogCreate: {
      /**
       * Title
       * @description Blog title
       */
      title: string;
      /**
       * Body
       * @description Blog body
       */
      body: string;
      /**
       * Tags
       * @description Blog tags
       */
      tags: string[];
      /**
       * Published
       * @description Blog published status
       */
      published: boolean;
      /**
       * Cover Url
       * @description Blog cover URL
       */
      cover_url?: string | null;
    };
    /** BlogListResponse */
    BlogListResponse: {
      /**
       * Items
       * @description Blog list
       */
      items: components["schemas"]["BlogResponse"][];
      /**
       * Total
       * @description Total count
       */
      total: number;
      /**
       * Page
       * @description Current page
       */
      page: number;
      /**
       * Page Size
       * @description Page size
       */
      page_size: number;
      /**
       * Total Pages
       * @description Total pages
       */
      total_pages: number;
    };
    /** BlogResponse */
    BlogResponse: {
      /**
       * Id
       * @description Blog id
       */
      id: number;
      /**
       * User Uuid
       * @description User UUID
       */
      user_uuid: string;
      /**
       * Title
       * @description Blog title
       */
      title: string;
      /**
       * Cover Url
       * @description Blog cover URL
       */
      cover_url: string | null;
      /**
       * Body
       * @description Blog body
       */
      body: string;
      /**
       * Tags Name
       * @description Blog tags
       */
      tags_name: string[];
      /**
       * Created At
       * Format: date-time
       * @description Blog creation time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       * @description Blog update time
       */
      updated_at: string;
      /**
       * View Count
       * @description Blog view count
       */
      view_count: number;
      /**
       * Likes Count
       * @description Blog like count
       */
      likes_count: number;
      /**
       * Published
       * @description Blog published status
       */
      published: boolean;
    };
    /** Body_image_upload_apis_v1_img_bed__post */
    Body_image_upload_apis_v1_img_bed__post: {
      /** Image */
      image: string;
    };
    /** Comment */
    Comment: {
      /** Id */
      id: number;
      /** Content */
      content: string;
      /**
       * Created At
       * Format: date-time
       */
      created_at: string;
      /**
       * Updated At
       * Format: date-time
       */
      updated_at: string;
      /** User Id */
      user_id: number;
      /** Blog Id */
      blog_id: number;
      /** Reply To Id */
      reply_to_id?: number | null;
    };
    /** CommentCreate */
    CommentCreate: {
      /** Blog Id */
      blog_id: number;
      /** Content */
      content: string;
      /** Reply To Id */
      reply_to_id?: number | null;
    };
    /** CommentsResponse */
    CommentsResponse: {
      /**
       * Comments
       * @default []
       */
      comments: components["schemas"]["Comment"][];
      /**
       * Total
       * @default 0
       */
      total: number;
    };
    /** ForgotPasswordRequest */
    ForgotPasswordRequest: {
      /**
       * Email
       * @description 用户邮箱
       */
      email: string;
    };
    /** HTTPValidationError */
    HTTPValidationError: {
      /** Detail */
      detail?: components["schemas"]["ValidationError"][];
    };
    /** LoginResponse */
    LoginResponse: {
      /**
       * User Uuid
       * @description 用户UUID
       */
      user_uuid: string;
      /**
       * Access Token
       * @description 访问令牌
       */
      access_token: string;
    };
    /** MessageResponse */
    MessageResponse: {
      /**
       * Message
       * @description 消息
       */
      message: string;
    };
    /** PermissionsResponse */
    PermissionsResponse: {
      /** Permissions */
      permissions: string[];
    };
    /** ResetPasswordRequest */
    ResetPasswordRequest: {
      /**
       * Token
       * @description 重置令牌
       */
      token: string;
      /**
       * New Password
       * @description 新密码
       */
      new_password: string;
    };
    /** UpdateUserRoleRequest */
    UpdateUserRoleRequest: {
      /** Role Ids */
      role_ids: number[];
    };
    /** UserCreate */
    UserCreate: {
      /**
       * Username
       * @description 用户名
       */
      username: string;
      /**
       * Password
       * @description 密码
       */
      password: string;
      /**
       * Email
       * @description 邮箱
       */
      email: string;
    };
    /** UserEdit */
    UserEdit: {
      /**
       * Username
       * @description 用户名
       */
      username?: string | null;
      /**
       * Email
       * @description 邮箱
       */
      email?: string | null;
      /**
       * Avatar
       * @description 头像
       */
      avatar?: string | null;
      /**
       * Gender
       * @description 性别
       */
      gender?: string | null;
      /**
       * Birthday
       * @description 生日
       */
      birthday?: string | null;
      /**
       * Location
       * @description 位置
       */
      location?: string | null;
      /**
       * Bio
       * @description 个人简介
       */
      bio?: string | null;
    };
    /** UserLogin */
    UserLogin: {
      /**
       * Evidence
       * @description 用户名或邮箱或其他证据
       */
      evidence: string;
      /**
       * Password
       * @description 密码
       */
      password: string;
    };
    /** UserRegisterResponse */
    UserRegisterResponse: {
      /**
       * User Uuid
       * @description 用户UUID
       */
      user_uuid: string;
    };
    /** UserResponse */
    UserResponse: {
      /**
       * Id
       * @description 用户ID
       */
      id: number;
      /**
       * Uuid
       * @description 用户UUID
       */
      uuid: string;
      /**
       * Username
       * @description 用户名
       */
      username: string;
      /**
       * Email
       * @description 邮箱
       */
      email: string;
      /**
       * Bio
       * @description 个人简介
       */
      bio: string | null;
      /**
       * Avatar
       * @description 头像
       */
      avatar: string | null;
    };
    /** ValidationError */
    ValidationError: {
      /** Location */
      loc: (string | number)[];
      /** Message */
      msg: string;
      /** Error Type */
      type: string;
      /** Input */
      input?: unknown;
      /** Context */
      ctx?: Record<string, never>;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  read_root__get: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
    };
  };
  get_blogs_apis_v1_blog__get: {
    parameters: {
      query?: {
        /** @description Page number */
        page?: number;
        /** @description Page size */
        page_size?: number;
        /** @description Filter by tag */
        tag?: string | null;
        /** @description Search in title and body */
        search?: string | null;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_blog_apis_v1_blog__post: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlogCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_blog_apis_v1_blog__id__get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_blog_apis_v1_blog__id__put: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["BlogCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["BlogResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_blog_apis_v1_blog__id__delete: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_like_status_apis_v1_blog__id__like_get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  toggle_like_apis_v1_blog__id__like_post: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  register_user_apis_v1_auth_register_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserRegisterResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  verify_email_apis_v1_auth_verify__token__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        token: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "text/html": string;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  login_apis_v1_auth_login_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserLogin"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  forgot_password_apis_v1_auth_forgot_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ForgotPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  reset_password_apis_v1_auth_reset_password_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["ResetPasswordRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["MessageResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  refresh_token_apis_v1_auth_refresh_post: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["LoginResponse"];
        };
      };
    };
  };
  image_upload_apis_v1_img_bed__post: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "multipart/form-data": components["schemas"]["Body_image_upload_apis_v1_img_bed__post"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  image_get_apis_v1_img_bed__object_name__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        object_name: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_permission_apis_v1_permission__get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PermissionsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  have_permission_apis_v1_permission__post: {
    parameters: {
      query: {
        permission_code: string;
      };
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": boolean;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_info_apis_v1_user_info_get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_user_info_by_id_apis_v1_user_info__user_uuid__get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        user_uuid: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  edit_user_info_apis_v1_user_edit_post: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UserEdit"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["UserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  create_comment_apis_v1_comment_create_post: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CommentCreate"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_comments_apis_v1_comment_get__blog_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        blog_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["CommentsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_comment_apis_v1_comment_get__comment_id__get: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Comment"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_comment_apis_v1_comment_delete__comment_id__delete: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_comment_apis_v1_comment_update__comment_id__put: {
    parameters: {
      query: {
        blog_id: number;
        content: string;
        reply_to_id?: number | null;
      };
      header?: {
        Authorization?: string | null;
      };
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_stats_apis_v1_admin_stats_get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminStatsResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_users_apis_v1_admin_users_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  update_user_roles_apis_v1_admin_users__user_id__role_put: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateUserRoleRequest"];
      };
    };
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminUserResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_user_apis_v1_admin_users__user_id__delete: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        user_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_blogs_apis_v1_admin_blogs_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
        published?: boolean | null;
      };
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminBlogListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  toggle_blog_publish_apis_v1_admin_blogs__blog_id__publish_put: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        blog_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_blog_apis_v1_admin_blogs__blog_id__delete: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        blog_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_comments_apis_v1_admin_comments_get: {
    parameters: {
      query?: {
        page?: number;
        page_size?: number;
      };
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminCommentListResponse"];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  delete_comment_apis_v1_admin_comments__comment_id__delete: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path: {
        comment_id: number;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": unknown;
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
  get_roles_apis_v1_admin_roles_get: {
    parameters: {
      query?: never;
      header?: {
        Authorization?: string | null;
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Successful Response */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["AdminRoleResponse"][];
        };
      };
      /** @description Validation Error */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HTTPValidationError"];
        };
      };
    };
  };
}
