// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
} from "./client";
import { client } from "./client.gen";
import type {
  CreateBlogApisV1BlogPostData,
  CreateBlogApisV1BlogPostErrors,
  CreateBlogApisV1BlogPostResponses,
  CreateCommentApisV1CommentCreatePostData,
  CreateCommentApisV1CommentCreatePostErrors,
  CreateCommentApisV1CommentCreatePostResponses,
  DeleteBlogApisV1AdminBlogsBlogIdDeleteData,
  DeleteBlogApisV1AdminBlogsBlogIdDeleteErrors,
  DeleteBlogApisV1AdminBlogsBlogIdDeleteResponses,
  DeleteBlogApisV1BlogIdDeleteData,
  DeleteBlogApisV1BlogIdDeleteErrors,
  DeleteBlogApisV1BlogIdDeleteResponses,
  DeleteCommentApisV1AdminCommentsCommentIdDeleteData,
  DeleteCommentApisV1AdminCommentsCommentIdDeleteErrors,
  DeleteCommentApisV1AdminCommentsCommentIdDeleteResponses,
  DeleteCommentApisV1CommentDeleteCommentIdDeleteData,
  DeleteCommentApisV1CommentDeleteCommentIdDeleteErrors,
  DeleteCommentApisV1CommentDeleteCommentIdDeleteResponses,
  DeleteUserApisV1AdminUsersUserIdDeleteData,
  DeleteUserApisV1AdminUsersUserIdDeleteErrors,
  DeleteUserApisV1AdminUsersUserIdDeleteResponses,
  EditUserInfoApisV1UserEditPostData,
  EditUserInfoApisV1UserEditPostErrors,
  EditUserInfoApisV1UserEditPostResponses,
  ForgotPasswordApisV1AuthForgotPasswordPostData,
  ForgotPasswordApisV1AuthForgotPasswordPostErrors,
  ForgotPasswordApisV1AuthForgotPasswordPostResponses,
  GetBlogApisV1BlogIdGetData,
  GetBlogApisV1BlogIdGetErrors,
  GetBlogApisV1BlogIdGetResponses,
  GetBlogsApisV1AdminBlogsGetData,
  GetBlogsApisV1AdminBlogsGetErrors,
  GetBlogsApisV1AdminBlogsGetResponses,
  GetBlogsApisV1BlogGetData,
  GetBlogsApisV1BlogGetErrors,
  GetBlogsApisV1BlogGetResponses,
  GetCommentApisV1CommentGetCommentIdGetData,
  GetCommentApisV1CommentGetCommentIdGetErrors,
  GetCommentApisV1CommentGetCommentIdGetResponses,
  GetCommentsApisV1AdminCommentsGetData,
  GetCommentsApisV1AdminCommentsGetErrors,
  GetCommentsApisV1AdminCommentsGetResponses,
  GetCommentsApisV1CommentGetBlogIdGetData,
  GetCommentsApisV1CommentGetBlogIdGetErrors,
  GetCommentsApisV1CommentGetBlogIdGetResponses,
  GetLikeStatusApisV1BlogIdLikeGetData,
  GetLikeStatusApisV1BlogIdLikeGetErrors,
  GetLikeStatusApisV1BlogIdLikeGetResponses,
  GetPermissionApisV1PermissionGetData,
  GetPermissionApisV1PermissionGetErrors,
  GetPermissionApisV1PermissionGetResponses,
  GetRolesApisV1AdminRolesGetData,
  GetRolesApisV1AdminRolesGetErrors,
  GetRolesApisV1AdminRolesGetResponses,
  GetStatsApisV1AdminStatsGetData,
  GetStatsApisV1AdminStatsGetErrors,
  GetStatsApisV1AdminStatsGetResponses,
  GetUserInfoApisV1UserInfoGetData,
  GetUserInfoApisV1UserInfoGetErrors,
  GetUserInfoApisV1UserInfoGetResponses,
  GetUserInfoByIdApisV1UserInfoUserUuidGetData,
  GetUserInfoByIdApisV1UserInfoUserUuidGetErrors,
  GetUserInfoByIdApisV1UserInfoUserUuidGetResponses,
  GetUsersApisV1AdminUsersGetData,
  GetUsersApisV1AdminUsersGetErrors,
  GetUsersApisV1AdminUsersGetResponses,
  HavePermissionApisV1PermissionPostData,
  HavePermissionApisV1PermissionPostErrors,
  HavePermissionApisV1PermissionPostResponses,
  ImageGetApisV1ImgBedObjectNameGetData,
  ImageGetApisV1ImgBedObjectNameGetErrors,
  ImageGetApisV1ImgBedObjectNameGetResponses,
  ImageUploadApisV1ImgBedPostData,
  ImageUploadApisV1ImgBedPostErrors,
  ImageUploadApisV1ImgBedPostResponses,
  LoginApisV1AuthLoginPostData,
  LoginApisV1AuthLoginPostErrors,
  LoginApisV1AuthLoginPostResponses,
  ReadRootGetData,
  ReadRootGetResponses,
  RefreshTokenApisV1AuthRefreshPostData,
  RefreshTokenApisV1AuthRefreshPostResponses,
  RegisterUserApisV1AuthRegisterPostData,
  RegisterUserApisV1AuthRegisterPostErrors,
  RegisterUserApisV1AuthRegisterPostResponses,
  ResetPasswordApisV1AuthResetPasswordPostData,
  ResetPasswordApisV1AuthResetPasswordPostErrors,
  ResetPasswordApisV1AuthResetPasswordPostResponses,
  ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutData,
  ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutErrors,
  ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutResponses,
  ToggleLikeApisV1BlogIdLikePostData,
  ToggleLikeApisV1BlogIdLikePostErrors,
  ToggleLikeApisV1BlogIdLikePostResponses,
  UpdateBlogApisV1BlogIdPutData,
  UpdateBlogApisV1BlogIdPutErrors,
  UpdateBlogApisV1BlogIdPutResponses,
  UpdateCommentApisV1CommentUpdateCommentIdPutData,
  UpdateCommentApisV1CommentUpdateCommentIdPutErrors,
  UpdateCommentApisV1CommentUpdateCommentIdPutResponses,
  UpdateUserRolesApisV1AdminUsersUserIdRolePutData,
  UpdateUserRolesApisV1AdminUsersUserIdRolePutErrors,
  UpdateUserRolesApisV1AdminUsersUserIdRolePutResponses,
  VerifyEmailApisV1AuthVerifyTokenGetData,
  VerifyEmailApisV1AuthVerifyTokenGetErrors,
  VerifyEmailApisV1AuthVerifyTokenGetResponses,
} from "./types.gen";

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Read Root
 */
export const readRootGet = <ThrowOnError extends boolean = false>(
  options?: Options<ReadRootGetData, ThrowOnError>,
): RequestResult<ReadRootGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<ReadRootGetResponses, unknown, ThrowOnError>({
    url: "/",
    ...options,
  });

/**
 * Get Blogs
 */
export const getBlogsApisV1BlogGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetBlogsApisV1BlogGetData, ThrowOnError>,
): RequestResult<
  GetBlogsApisV1BlogGetResponses,
  GetBlogsApisV1BlogGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetBlogsApisV1BlogGetResponses,
    GetBlogsApisV1BlogGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/blog/", ...options });

/**
 * Create Blog
 */
export const createBlogApisV1BlogPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateBlogApisV1BlogPostData, ThrowOnError>,
): RequestResult<
  CreateBlogApisV1BlogPostResponses,
  CreateBlogApisV1BlogPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateBlogApisV1BlogPostResponses,
    CreateBlogApisV1BlogPostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/blog/",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete Blog
 */
export const deleteBlogApisV1BlogIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteBlogApisV1BlogIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteBlogApisV1BlogIdDeleteResponses,
  DeleteBlogApisV1BlogIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBlogApisV1BlogIdDeleteResponses,
    DeleteBlogApisV1BlogIdDeleteErrors,
    ThrowOnError
  >({ url: "/apis/v1/blog/{id}", ...options });

/**
 * Get Blog
 */
export const getBlogApisV1BlogIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetBlogApisV1BlogIdGetData, ThrowOnError>,
): RequestResult<
  GetBlogApisV1BlogIdGetResponses,
  GetBlogApisV1BlogIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetBlogApisV1BlogIdGetResponses,
    GetBlogApisV1BlogIdGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/blog/{id}", ...options });

/**
 * Update Blog
 */
export const updateBlogApisV1BlogIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateBlogApisV1BlogIdPutData, ThrowOnError>,
): RequestResult<
  UpdateBlogApisV1BlogIdPutResponses,
  UpdateBlogApisV1BlogIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateBlogApisV1BlogIdPutResponses,
    UpdateBlogApisV1BlogIdPutErrors,
    ThrowOnError
  >({
    url: "/apis/v1/blog/{id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Like Status
 */
export const getLikeStatusApisV1BlogIdLikeGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetLikeStatusApisV1BlogIdLikeGetData, ThrowOnError>,
): RequestResult<
  GetLikeStatusApisV1BlogIdLikeGetResponses,
  GetLikeStatusApisV1BlogIdLikeGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetLikeStatusApisV1BlogIdLikeGetResponses,
    GetLikeStatusApisV1BlogIdLikeGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/blog/{id}/like", ...options });

/**
 * Toggle Like
 */
export const toggleLikeApisV1BlogIdLikePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ToggleLikeApisV1BlogIdLikePostData, ThrowOnError>,
): RequestResult<
  ToggleLikeApisV1BlogIdLikePostResponses,
  ToggleLikeApisV1BlogIdLikePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ToggleLikeApisV1BlogIdLikePostResponses,
    ToggleLikeApisV1BlogIdLikePostErrors,
    ThrowOnError
  >({ url: "/apis/v1/blog/{id}/like", ...options });

/**
 * Register User
 */
export const registerUserApisV1AuthRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterUserApisV1AuthRegisterPostData, ThrowOnError>,
): RequestResult<
  RegisterUserApisV1AuthRegisterPostResponses,
  RegisterUserApisV1AuthRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterUserApisV1AuthRegisterPostResponses,
    RegisterUserApisV1AuthRegisterPostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/auth/register",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Verify Email
 *
 * 根据token对邮箱进行验证
 */
export const verifyEmailApisV1AuthVerifyTokenGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<VerifyEmailApisV1AuthVerifyTokenGetData, ThrowOnError>,
): RequestResult<
  VerifyEmailApisV1AuthVerifyTokenGetResponses,
  VerifyEmailApisV1AuthVerifyTokenGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    VerifyEmailApisV1AuthVerifyTokenGetResponses,
    VerifyEmailApisV1AuthVerifyTokenGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/auth/verify/{token}", ...options });

/**
 * Login
 */
export const loginApisV1AuthLoginPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginApisV1AuthLoginPostData, ThrowOnError>,
): RequestResult<
  LoginApisV1AuthLoginPostResponses,
  LoginApisV1AuthLoginPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginApisV1AuthLoginPostResponses,
    LoginApisV1AuthLoginPostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/auth/login",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Forgot Password
 *
 * 发送密码重置邮件
 */
export const forgotPasswordApisV1AuthForgotPasswordPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ForgotPasswordApisV1AuthForgotPasswordPostData,
    ThrowOnError
  >,
): RequestResult<
  ForgotPasswordApisV1AuthForgotPasswordPostResponses,
  ForgotPasswordApisV1AuthForgotPasswordPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ForgotPasswordApisV1AuthForgotPasswordPostResponses,
    ForgotPasswordApisV1AuthForgotPasswordPostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/auth/forgot-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Reset Password
 *
 * 使用令牌重置密码
 */
export const resetPasswordApisV1AuthResetPasswordPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ResetPasswordApisV1AuthResetPasswordPostData, ThrowOnError>,
): RequestResult<
  ResetPasswordApisV1AuthResetPasswordPostResponses,
  ResetPasswordApisV1AuthResetPasswordPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ResetPasswordApisV1AuthResetPasswordPostResponses,
    ResetPasswordApisV1AuthResetPasswordPostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/auth/reset-password",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Refresh Token
 *
 * 刷新访问令牌
 */
export const refreshTokenApisV1AuthRefreshPost = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<RefreshTokenApisV1AuthRefreshPostData, ThrowOnError>,
): RequestResult<
  RefreshTokenApisV1AuthRefreshPostResponses,
  unknown,
  ThrowOnError
> =>
  (options?.client ?? client).post<
    RefreshTokenApisV1AuthRefreshPostResponses,
    unknown,
    ThrowOnError
  >({ url: "/apis/v1/auth/refresh", ...options });

/**
 * Image Upload
 *
 * Upload an image file. Returns the public URL.
 *
 * The file is stored via StorageService (MinIO or local filesystem).
 */
export const imageUploadApisV1ImgBedPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ImageUploadApisV1ImgBedPostData, ThrowOnError>,
): RequestResult<
  ImageUploadApisV1ImgBedPostResponses,
  ImageUploadApisV1ImgBedPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ImageUploadApisV1ImgBedPostResponses,
    ImageUploadApisV1ImgBedPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    url: "/apis/v1/img_bed/",
    ...options,
    headers: {
      "Content-Type": null,
      ...options.headers,
    },
  });

/**
 * Image Get
 *
 * Get an image file by its hash-based filename.
 */
export const imageGetApisV1ImgBedObjectNameGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ImageGetApisV1ImgBedObjectNameGetData, ThrowOnError>,
): RequestResult<
  ImageGetApisV1ImgBedObjectNameGetResponses,
  ImageGetApisV1ImgBedObjectNameGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    ImageGetApisV1ImgBedObjectNameGetResponses,
    ImageGetApisV1ImgBedObjectNameGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/img_bed/{object_name}", ...options });

/**
 * Get Permission
 */
export const getPermissionApisV1PermissionGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetPermissionApisV1PermissionGetData, ThrowOnError>,
): RequestResult<
  GetPermissionApisV1PermissionGetResponses,
  GetPermissionApisV1PermissionGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetPermissionApisV1PermissionGetResponses,
    GetPermissionApisV1PermissionGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/permission/", ...options });

/**
 * Have Permission
 */
export const havePermissionApisV1PermissionPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<HavePermissionApisV1PermissionPostData, ThrowOnError>,
): RequestResult<
  HavePermissionApisV1PermissionPostResponses,
  HavePermissionApisV1PermissionPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    HavePermissionApisV1PermissionPostResponses,
    HavePermissionApisV1PermissionPostErrors,
    ThrowOnError
  >({ url: "/apis/v1/permission/", ...options });

/**
 * Get User Info
 */
export const getUserInfoApisV1UserInfoGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetUserInfoApisV1UserInfoGetData, ThrowOnError>,
): RequestResult<
  GetUserInfoApisV1UserInfoGetResponses,
  GetUserInfoApisV1UserInfoGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetUserInfoApisV1UserInfoGetResponses,
    GetUserInfoApisV1UserInfoGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/user/info", ...options });

/**
 * Get User Info By Id
 */
export const getUserInfoByIdApisV1UserInfoUserUuidGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetUserInfoByIdApisV1UserInfoUserUuidGetData, ThrowOnError>,
): RequestResult<
  GetUserInfoByIdApisV1UserInfoUserUuidGetResponses,
  GetUserInfoByIdApisV1UserInfoUserUuidGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetUserInfoByIdApisV1UserInfoUserUuidGetResponses,
    GetUserInfoByIdApisV1UserInfoUserUuidGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/user/info/{user_uuid}", ...options });

/**
 * Edit User Info
 */
export const editUserInfoApisV1UserEditPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<EditUserInfoApisV1UserEditPostData, ThrowOnError>,
): RequestResult<
  EditUserInfoApisV1UserEditPostResponses,
  EditUserInfoApisV1UserEditPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    EditUserInfoApisV1UserEditPostResponses,
    EditUserInfoApisV1UserEditPostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/user/edit",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Create Comment
 */
export const createCommentApisV1CommentCreatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateCommentApisV1CommentCreatePostData, ThrowOnError>,
): RequestResult<
  CreateCommentApisV1CommentCreatePostResponses,
  CreateCommentApisV1CommentCreatePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCommentApisV1CommentCreatePostResponses,
    CreateCommentApisV1CommentCreatePostErrors,
    ThrowOnError
  >({
    url: "/apis/v1/comment/create",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Comments
 */
export const getCommentsApisV1CommentGetBlogIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCommentsApisV1CommentGetBlogIdGetData, ThrowOnError>,
): RequestResult<
  GetCommentsApisV1CommentGetBlogIdGetResponses,
  GetCommentsApisV1CommentGetBlogIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCommentsApisV1CommentGetBlogIdGetResponses,
    GetCommentsApisV1CommentGetBlogIdGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/comment/get/{blog_id}", ...options });

/**
 * Get Comment
 */
export const getCommentApisV1CommentGetCommentIdGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetCommentApisV1CommentGetCommentIdGetData, ThrowOnError>,
): RequestResult<
  GetCommentApisV1CommentGetCommentIdGetResponses,
  GetCommentApisV1CommentGetCommentIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCommentApisV1CommentGetCommentIdGetResponses,
    GetCommentApisV1CommentGetCommentIdGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/comment/get/{comment_id}", ...options });

/**
 * Delete Comment
 */
export const deleteCommentApisV1CommentDeleteCommentIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCommentApisV1CommentDeleteCommentIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteCommentApisV1CommentDeleteCommentIdDeleteResponses,
  DeleteCommentApisV1CommentDeleteCommentIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCommentApisV1CommentDeleteCommentIdDeleteResponses,
    DeleteCommentApisV1CommentDeleteCommentIdDeleteErrors,
    ThrowOnError
  >({ url: "/apis/v1/comment/delete/{comment_id}", ...options });

/**
 * Update Comment
 */
export const updateCommentApisV1CommentUpdateCommentIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateCommentApisV1CommentUpdateCommentIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateCommentApisV1CommentUpdateCommentIdPutResponses,
  UpdateCommentApisV1CommentUpdateCommentIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCommentApisV1CommentUpdateCommentIdPutResponses,
    UpdateCommentApisV1CommentUpdateCommentIdPutErrors,
    ThrowOnError
  >({
    url: "/apis/v1/comment/update/{comment_id}",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Get Stats
 *
 * 获取仪表盘统计数据
 */
export const getStatsApisV1AdminStatsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetStatsApisV1AdminStatsGetData, ThrowOnError>,
): RequestResult<
  GetStatsApisV1AdminStatsGetResponses,
  GetStatsApisV1AdminStatsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetStatsApisV1AdminStatsGetResponses,
    GetStatsApisV1AdminStatsGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/stats", ...options });

/**
 * Get Users
 *
 * 获取用户列表
 */
export const getUsersApisV1AdminUsersGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetUsersApisV1AdminUsersGetData, ThrowOnError>,
): RequestResult<
  GetUsersApisV1AdminUsersGetResponses,
  GetUsersApisV1AdminUsersGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetUsersApisV1AdminUsersGetResponses,
    GetUsersApisV1AdminUsersGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/users", ...options });

/**
 * Update User Roles
 *
 * 更新用户角色
 */
export const updateUserRolesApisV1AdminUsersUserIdRolePut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateUserRolesApisV1AdminUsersUserIdRolePutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateUserRolesApisV1AdminUsersUserIdRolePutResponses,
  UpdateUserRolesApisV1AdminUsersUserIdRolePutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateUserRolesApisV1AdminUsersUserIdRolePutResponses,
    UpdateUserRolesApisV1AdminUsersUserIdRolePutErrors,
    ThrowOnError
  >({
    url: "/apis/v1/admin/users/{user_id}/role",
    ...options,
    headers: {
      "Content-Type": "application/json",
      ...options.headers,
    },
  });

/**
 * Delete User
 *
 * 删除用户
 */
export const deleteUserApisV1AdminUsersUserIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteUserApisV1AdminUsersUserIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteUserApisV1AdminUsersUserIdDeleteResponses,
  DeleteUserApisV1AdminUsersUserIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteUserApisV1AdminUsersUserIdDeleteResponses,
    DeleteUserApisV1AdminUsersUserIdDeleteErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/users/{user_id}", ...options });

/**
 * Get Blogs
 *
 * 获取文章列表(包含未发布的)
 */
export const getBlogsApisV1AdminBlogsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetBlogsApisV1AdminBlogsGetData, ThrowOnError>,
): RequestResult<
  GetBlogsApisV1AdminBlogsGetResponses,
  GetBlogsApisV1AdminBlogsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetBlogsApisV1AdminBlogsGetResponses,
    GetBlogsApisV1AdminBlogsGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/blogs", ...options });

/**
 * Toggle Blog Publish
 *
 * 切换文章发布状态
 */
export const toggleBlogPublishApisV1AdminBlogsBlogIdPublishPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutData,
    ThrowOnError
  >,
): RequestResult<
  ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutResponses,
  ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutResponses,
    ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/blogs/{blog_id}/publish", ...options });

/**
 * Delete Blog
 *
 * 删除文章
 */
export const deleteBlogApisV1AdminBlogsBlogIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteBlogApisV1AdminBlogsBlogIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteBlogApisV1AdminBlogsBlogIdDeleteResponses,
  DeleteBlogApisV1AdminBlogsBlogIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteBlogApisV1AdminBlogsBlogIdDeleteResponses,
    DeleteBlogApisV1AdminBlogsBlogIdDeleteErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/blogs/{blog_id}", ...options });

/**
 * Get Comments
 *
 * 获取评论列表
 */
export const getCommentsApisV1AdminCommentsGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetCommentsApisV1AdminCommentsGetData, ThrowOnError>,
): RequestResult<
  GetCommentsApisV1AdminCommentsGetResponses,
  GetCommentsApisV1AdminCommentsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetCommentsApisV1AdminCommentsGetResponses,
    GetCommentsApisV1AdminCommentsGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/comments", ...options });

/**
 * Delete Comment
 *
 * 删除评论
 */
export const deleteCommentApisV1AdminCommentsCommentIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteCommentApisV1AdminCommentsCommentIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteCommentApisV1AdminCommentsCommentIdDeleteResponses,
  DeleteCommentApisV1AdminCommentsCommentIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCommentApisV1AdminCommentsCommentIdDeleteResponses,
    DeleteCommentApisV1AdminCommentsCommentIdDeleteErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/comments/{comment_id}", ...options });

/**
 * Get Roles
 *
 * 获取所有角色
 */
export const getRolesApisV1AdminRolesGet = <
  ThrowOnError extends boolean = false,
>(
  options?: Options<GetRolesApisV1AdminRolesGetData, ThrowOnError>,
): RequestResult<
  GetRolesApisV1AdminRolesGetResponses,
  GetRolesApisV1AdminRolesGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetRolesApisV1AdminRolesGetResponses,
    GetRolesApisV1AdminRolesGetErrors,
    ThrowOnError
  >({ url: "/apis/v1/admin/roles", ...options });
