// This file is auto-generated by @hey-api/openapi-ts

import type {
  CreateBlogApisV1BlogPostResponse,
  CreateCommentApisV1CommentCreatePostResponse,
  GetBlogApisV1BlogIdGetResponse,
  GetBlogsApisV1BlogGetResponse,
  GetCommentApisV1CommentGetCommentIdGetResponse,
  GetCommentsApisV1CommentGetBlogIdGetResponse,
  UpdateBlogApisV1BlogIdPutResponse,
} from "./types.gen";

const blogResponseSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

const blogListResponseSchemaResponseTransformer = (data: any) => {
  data.items = data.items.map((item: any) =>
    blogResponseSchemaResponseTransformer(item),
  );
  return data;
};

export const getBlogsApisV1BlogGetResponseTransformer = async (
  data: any,
): Promise<GetBlogsApisV1BlogGetResponse> => {
  data = blogListResponseSchemaResponseTransformer(data);
  return data;
};

export const createBlogApisV1BlogPostResponseTransformer = async (
  data: any,
): Promise<CreateBlogApisV1BlogPostResponse> => {
  data = blogResponseSchemaResponseTransformer(data);
  return data;
};

export const getBlogApisV1BlogIdGetResponseTransformer = async (
  data: any,
): Promise<GetBlogApisV1BlogIdGetResponse> => {
  data = blogResponseSchemaResponseTransformer(data);
  return data;
};

export const updateBlogApisV1BlogIdPutResponseTransformer = async (
  data: any,
): Promise<UpdateBlogApisV1BlogIdPutResponse> => {
  data = blogResponseSchemaResponseTransformer(data);
  return data;
};

const commentSchemaResponseTransformer = (data: any) => {
  data.created_at = new Date(data.created_at);
  data.updated_at = new Date(data.updated_at);
  return data;
};

export const createCommentApisV1CommentCreatePostResponseTransformer = async (
  data: any,
): Promise<CreateCommentApisV1CommentCreatePostResponse> => {
  data = commentSchemaResponseTransformer(data);
  return data;
};

const commentsResponseSchemaResponseTransformer = (data: any) => {
  if (data.comments) {
    data.comments = data.comments.map((item: any) =>
      commentSchemaResponseTransformer(item),
    );
  }
  return data;
};

export const getCommentsApisV1CommentGetBlogIdGetResponseTransformer = async (
  data: any,
): Promise<GetCommentsApisV1CommentGetBlogIdGetResponse> => {
  data = commentsResponseSchemaResponseTransformer(data);
  return data;
};

export const getCommentApisV1CommentGetCommentIdGetResponseTransformer = async (
  data: any,
): Promise<GetCommentApisV1CommentGetCommentIdGetResponse> => {
  data = commentSchemaResponseTransformer(data);
  return data;
};
