// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseUrl: `${string}://${string}` | (string & {});
};

/**
 * AdminBlogListResponse
 */
export type AdminBlogListResponse = {
  /**
   * Items
   */
  items: Array<AdminBlogResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * AdminBlogResponse
 */
export type AdminBlogResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * User Uuid
   */
  user_uuid: string;
  /**
   * Username
   */
  username: string;
  /**
   * Title
   */
  title: string;
  /**
   * Cover Url
   */
  cover_url: string | null;
  /**
   * Tags Name
   */
  tags_name: Array<string>;
  /**
   * Created At
   */
  created_at: number;
  /**
   * Updated At
   */
  updated_at: number;
  /**
   * View Count
   */
  view_count: number;
  /**
   * Likes Count
   */
  likes_count: number;
  /**
   * Published
   */
  published: boolean;
};

/**
 * AdminCommentListResponse
 */
export type AdminCommentListResponse = {
  /**
   * Items
   */
  items: Array<AdminCommentResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * AdminCommentResponse
 */
export type AdminCommentResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Blog Id
   */
  blog_id: number;
  /**
   * Blog Title
   */
  blog_title: string;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Username
   */
  username: string;
  /**
   * Content
   */
  content: string;
  /**
   * Created At
   */
  created_at: number;
  /**
   * Updated At
   */
  updated_at: number;
};

/**
 * AdminRoleResponse
 */
export type AdminRoleResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Name
   */
  name: string;
  /**
   * Description
   */
  description: string | null;
  /**
   * Is Default
   */
  is_default: boolean;
  /**
   * Permissions
   */
  permissions?: Array<string>;
};

/**
 * AdminStatsResponse
 */
export type AdminStatsResponse = {
  /**
   * Total Users
   */
  total_users: number;
  /**
   * Total Blogs
   */
  total_blogs: number;
  /**
   * Total Comments
   */
  total_comments: number;
  /**
   * Total Blogs Today
   */
  total_blogs_today: number;
  /**
   * Total Comments Today
   */
  total_comments_today: number;
  /**
   * Recent Blogs
   */
  recent_blogs?: Array<AdminBlogResponse>;
  /**
   * Recent Comments
   */
  recent_comments?: Array<AdminCommentResponse>;
};

/**
 * AdminUserListResponse
 */
export type AdminUserListResponse = {
  /**
   * Items
   */
  items: Array<AdminUserResponse>;
  /**
   * Total
   */
  total: number;
  /**
   * Page
   */
  page: number;
  /**
   * Page Size
   */
  page_size: number;
  /**
   * Total Pages
   */
  total_pages: number;
};

/**
 * AdminUserResponse
 */
export type AdminUserResponse = {
  /**
   * Id
   */
  id: number;
  /**
   * Uuid
   */
  uuid: string;
  /**
   * Username
   */
  username: string;
  /**
   * Email
   */
  email: string;
  /**
   * Is Verified
   */
  is_verified: boolean;
  /**
   * Created At
   */
  created_at: number;
  /**
   * Roles
   */
  roles?: Array<string>;
};

/**
 * BlogCreate
 */
export type BlogCreate = {
  /**
   * Title
   *
   * Blog title
   */
  title: string;
  /**
   * Body
   *
   * Blog body
   */
  body: string;
  /**
   * Tags
   *
   * Blog tags
   */
  tags: Array<string>;
  /**
   * Published
   *
   * Blog published status
   */
  published: boolean;
  /**
   * Cover Url
   *
   * Blog cover URL
   */
  cover_url?: string | null;
};

/**
 * BlogListResponse
 */
export type BlogListResponse = {
  /**
   * Items
   *
   * Blog list
   */
  items: Array<BlogResponse>;
  /**
   * Total
   *
   * Total count
   */
  total: number;
  /**
   * Page
   *
   * Current page
   */
  page: number;
  /**
   * Page Size
   *
   * Page size
   */
  page_size: number;
  /**
   * Total Pages
   *
   * Total pages
   */
  total_pages: number;
};

/**
 * BlogResponse
 */
export type BlogResponse = {
  /**
   * Id
   *
   * Blog id
   */
  id: number;
  /**
   * User Uuid
   *
   * User UUID
   */
  user_uuid: string;
  /**
   * Title
   *
   * Blog title
   */
  title: string;
  /**
   * Cover Url
   *
   * Blog cover URL
   */
  cover_url: string | null;
  /**
   * Body
   *
   * Blog body
   */
  body: string;
  /**
   * Tags Name
   *
   * Blog tags
   */
  tags_name: Array<string>;
  /**
   * Created At
   *
   * Blog creation time
   */
  created_at: Date;
  /**
   * Updated At
   *
   * Blog update time
   */
  updated_at: Date;
  /**
   * View Count
   *
   * Blog view count
   */
  view_count: number;
  /**
   * Likes Count
   *
   * Blog like count
   */
  likes_count: number;
  /**
   * Published
   *
   * Blog published status
   */
  published: boolean;
};

/**
 * Body_image_upload_apis_v1_img_bed__post
 */
export type BodyImageUploadApisV1ImgBedPost = {
  /**
   * Image
   */
  image: Blob | File;
};

/**
 * Comment
 */
export type Comment = {
  /**
   * Id
   */
  id: number;
  /**
   * Content
   */
  content: string;
  /**
   * Created At
   */
  created_at: Date;
  /**
   * Updated At
   */
  updated_at: Date;
  /**
   * User Id
   */
  user_id: number;
  /**
   * Blog Id
   */
  blog_id: number;
  /**
   * Reply To Id
   */
  reply_to_id?: number | null;
};

/**
 * CommentCreate
 */
export type CommentCreate = {
  /**
   * Blog Id
   */
  blog_id: number;
  /**
   * Content
   */
  content: string;
  /**
   * Reply To Id
   */
  reply_to_id?: number | null;
};

/**
 * CommentsResponse
 */
export type CommentsResponse = {
  /**
   * Comments
   */
  comments?: Array<Comment>;
  /**
   * Total
   */
  total?: number;
};

/**
 * ForgotPasswordRequest
 */
export type ForgotPasswordRequest = {
  /**
   * Email
   *
   * 用户邮箱
   */
  email: string;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
  /**
   * Detail
   */
  detail?: Array<ValidationError>;
};

/**
 * ImageUploadResponse
 */
export type ImageUploadResponse = {
  /**
   * Url
   *
   * Public URL of the uploaded image
   */
  url: string;
};

/**
 * LikeStatusResponse
 */
export type LikeStatusResponse = {
  /**
   * Likes Count
   *
   * Total like count
   */
  likes_count: number;
};

/**
 * LikeToggleResponse
 */
export type LikeToggleResponse = {
  /**
   * Liked
   *
   * Whether the blog is liked after toggling
   */
  liked: boolean;
  /**
   * Likes Count
   *
   * Total like count
   */
  likes_count: number;
};

/**
 * LoginResponse
 */
export type LoginResponse = {
  /**
   * User Uuid
   *
   * 用户UUID
   */
  user_uuid: string;
  /**
   * Access Token
   *
   * 访问令牌
   */
  access_token: string;
};

/**
 * MessageResponse
 */
export type MessageResponse = {
  /**
   * Message
   *
   * 消息
   */
  message: string;
};

/**
 * PermissionsResponse
 */
export type PermissionsResponse = {
  /**
   * Permissions
   */
  permissions: Array<string>;
};

/**
 * ResetPasswordRequest
 */
export type ResetPasswordRequest = {
  /**
   * Token
   *
   * 重置令牌
   */
  token: string;
  /**
   * New Password
   *
   * 新密码
   */
  new_password: string;
};

/**
 * UpdateUserRoleRequest
 */
export type UpdateUserRoleRequest = {
  /**
   * Role Ids
   */
  role_ids: Array<number>;
};

/**
 * UserCreate
 */
export type UserCreate = {
  /**
   * Username
   *
   * 用户名
   */
  username: string;
  /**
   * Password
   *
   * 密码
   */
  password: string;
  /**
   * Email
   *
   * 邮箱
   */
  email: string;
};

/**
 * UserEdit
 */
export type UserEdit = {
  /**
   * Username
   *
   * 用户名
   */
  username?: string | null;
  /**
   * Email
   *
   * 邮箱
   */
  email?: string | null;
  /**
   * Avatar
   *
   * 头像
   */
  avatar?: string | null;
  /**
   * Gender
   *
   * 性别
   */
  gender?: string | null;
  /**
   * Birthday
   *
   * 生日
   */
  birthday?: string | null;
  /**
   * Location
   *
   * 位置
   */
  location?: string | null;
  /**
   * Bio
   *
   * 个人简介
   */
  bio?: string | null;
};

/**
 * UserLogin
 */
export type UserLogin = {
  /**
   * Evidence
   *
   * 用户名或邮箱或其他证据
   */
  evidence: string;
  /**
   * Password
   *
   * 密码
   */
  password: string;
};

/**
 * UserRegisterResponse
 */
export type UserRegisterResponse = {
  /**
   * User Uuid
   *
   * 用户UUID
   */
  user_uuid: string;
};

/**
 * UserResponse
 */
export type UserResponse = {
  /**
   * Id
   *
   * 用户ID
   */
  id: number;
  /**
   * Uuid
   *
   * 用户UUID
   */
  uuid: string;
  /**
   * Username
   *
   * 用户名
   */
  username: string;
  /**
   * Email
   *
   * 邮箱
   */
  email: string;
  /**
   * Bio
   *
   * 个人简介
   */
  bio: string | null;
  /**
   * Avatar
   *
   * 头像
   */
  avatar: string | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
  /**
   * Location
   */
  loc: Array<string | number>;
  /**
   * Message
   */
  msg: string;
  /**
   * Error Type
   */
  type: string;
  /**
   * Input
   */
  input?: unknown;
  /**
   * Context
   */
  ctx?: {
    [key: string]: unknown;
  };
};

export type ReadRootGetData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/";
};

export type ReadRootGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetBlogsApisV1BlogGetData = {
  body?: never;
  path?: never;
  query?: {
    /**
     * Page
     *
     * Page number
     */
    page?: number;
    /**
     * Page Size
     *
     * Page size
     */
    page_size?: number;
    /**
     * Tag
     *
     * Filter by tag
     */
    tag?: string | null;
    /**
     * Search
     *
     * Search in title and body
     */
    search?: string | null;
    /**
     * User Id
     *
     * Filter by user UUID
     */
    user_id?: string | null;
  };
  url: "/apis/v1/blog/";
};

export type GetBlogsApisV1BlogGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBlogsApisV1BlogGetError =
  GetBlogsApisV1BlogGetErrors[keyof GetBlogsApisV1BlogGetErrors];

export type GetBlogsApisV1BlogGetResponses = {
  /**
   * Successful Response
   */
  200: BlogListResponse;
};

export type GetBlogsApisV1BlogGetResponse =
  GetBlogsApisV1BlogGetResponses[keyof GetBlogsApisV1BlogGetResponses];

export type CreateBlogApisV1BlogPostData = {
  body: BlogCreate;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/blog/";
};

export type CreateBlogApisV1BlogPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateBlogApisV1BlogPostError =
  CreateBlogApisV1BlogPostErrors[keyof CreateBlogApisV1BlogPostErrors];

export type CreateBlogApisV1BlogPostResponses = {
  /**
   * Successful Response
   */
  200: BlogResponse;
};

export type CreateBlogApisV1BlogPostResponse =
  CreateBlogApisV1BlogPostResponses[keyof CreateBlogApisV1BlogPostResponses];

export type DeleteBlogApisV1BlogIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/apis/v1/blog/{id}";
};

export type DeleteBlogApisV1BlogIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteBlogApisV1BlogIdDeleteError =
  DeleteBlogApisV1BlogIdDeleteErrors[keyof DeleteBlogApisV1BlogIdDeleteErrors];

export type DeleteBlogApisV1BlogIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetBlogApisV1BlogIdGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/apis/v1/blog/{id}";
};

export type GetBlogApisV1BlogIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBlogApisV1BlogIdGetError =
  GetBlogApisV1BlogIdGetErrors[keyof GetBlogApisV1BlogIdGetErrors];

export type GetBlogApisV1BlogIdGetResponses = {
  /**
   * Successful Response
   */
  200: BlogResponse;
};

export type GetBlogApisV1BlogIdGetResponse =
  GetBlogApisV1BlogIdGetResponses[keyof GetBlogApisV1BlogIdGetResponses];

export type UpdateBlogApisV1BlogIdPutData = {
  body: BlogCreate;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/apis/v1/blog/{id}";
};

export type UpdateBlogApisV1BlogIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateBlogApisV1BlogIdPutError =
  UpdateBlogApisV1BlogIdPutErrors[keyof UpdateBlogApisV1BlogIdPutErrors];

export type UpdateBlogApisV1BlogIdPutResponses = {
  /**
   * Successful Response
   */
  200: BlogResponse;
};

export type UpdateBlogApisV1BlogIdPutResponse =
  UpdateBlogApisV1BlogIdPutResponses[keyof UpdateBlogApisV1BlogIdPutResponses];

export type GetLikeStatusApisV1BlogIdLikeGetData = {
  body?: never;
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/apis/v1/blog/{id}/like";
};

export type GetLikeStatusApisV1BlogIdLikeGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetLikeStatusApisV1BlogIdLikeGetError =
  GetLikeStatusApisV1BlogIdLikeGetErrors[keyof GetLikeStatusApisV1BlogIdLikeGetErrors];

export type GetLikeStatusApisV1BlogIdLikeGetResponses = {
  /**
   * Successful Response
   */
  200: LikeStatusResponse;
};

export type GetLikeStatusApisV1BlogIdLikeGetResponse =
  GetLikeStatusApisV1BlogIdLikeGetResponses[keyof GetLikeStatusApisV1BlogIdLikeGetResponses];

export type ToggleLikeApisV1BlogIdLikePostData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Id
     */
    id: number;
  };
  query?: never;
  url: "/apis/v1/blog/{id}/like";
};

export type ToggleLikeApisV1BlogIdLikePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ToggleLikeApisV1BlogIdLikePostError =
  ToggleLikeApisV1BlogIdLikePostErrors[keyof ToggleLikeApisV1BlogIdLikePostErrors];

export type ToggleLikeApisV1BlogIdLikePostResponses = {
  /**
   * Successful Response
   */
  200: LikeToggleResponse;
};

export type ToggleLikeApisV1BlogIdLikePostResponse =
  ToggleLikeApisV1BlogIdLikePostResponses[keyof ToggleLikeApisV1BlogIdLikePostResponses];

export type RegisterUserApisV1AuthRegisterPostData = {
  body: UserCreate;
  path?: never;
  query?: never;
  url: "/apis/v1/auth/register";
};

export type RegisterUserApisV1AuthRegisterPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type RegisterUserApisV1AuthRegisterPostError =
  RegisterUserApisV1AuthRegisterPostErrors[keyof RegisterUserApisV1AuthRegisterPostErrors];

export type RegisterUserApisV1AuthRegisterPostResponses = {
  /**
   * Successful Response
   */
  200: UserRegisterResponse;
};

export type RegisterUserApisV1AuthRegisterPostResponse =
  RegisterUserApisV1AuthRegisterPostResponses[keyof RegisterUserApisV1AuthRegisterPostResponses];

export type VerifyEmailApisV1AuthVerifyTokenGetData = {
  body?: never;
  path: {
    /**
     * Token
     */
    token: string;
  };
  query?: never;
  url: "/apis/v1/auth/verify/{token}";
};

export type VerifyEmailApisV1AuthVerifyTokenGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type VerifyEmailApisV1AuthVerifyTokenGetError =
  VerifyEmailApisV1AuthVerifyTokenGetErrors[keyof VerifyEmailApisV1AuthVerifyTokenGetErrors];

export type VerifyEmailApisV1AuthVerifyTokenGetResponses = {
  /**
   * Successful Response
   */
  200: string;
};

export type VerifyEmailApisV1AuthVerifyTokenGetResponse =
  VerifyEmailApisV1AuthVerifyTokenGetResponses[keyof VerifyEmailApisV1AuthVerifyTokenGetResponses];

export type LoginApisV1AuthLoginPostData = {
  body: UserLogin;
  path?: never;
  query?: never;
  url: "/apis/v1/auth/login";
};

export type LoginApisV1AuthLoginPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type LoginApisV1AuthLoginPostError =
  LoginApisV1AuthLoginPostErrors[keyof LoginApisV1AuthLoginPostErrors];

export type LoginApisV1AuthLoginPostResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type LoginApisV1AuthLoginPostResponse =
  LoginApisV1AuthLoginPostResponses[keyof LoginApisV1AuthLoginPostResponses];

export type ForgotPasswordApisV1AuthForgotPasswordPostData = {
  body: ForgotPasswordRequest;
  path?: never;
  query?: never;
  url: "/apis/v1/auth/forgot-password";
};

export type ForgotPasswordApisV1AuthForgotPasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ForgotPasswordApisV1AuthForgotPasswordPostError =
  ForgotPasswordApisV1AuthForgotPasswordPostErrors[keyof ForgotPasswordApisV1AuthForgotPasswordPostErrors];

export type ForgotPasswordApisV1AuthForgotPasswordPostResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type ForgotPasswordApisV1AuthForgotPasswordPostResponse =
  ForgotPasswordApisV1AuthForgotPasswordPostResponses[keyof ForgotPasswordApisV1AuthForgotPasswordPostResponses];

export type ResetPasswordApisV1AuthResetPasswordPostData = {
  body: ResetPasswordRequest;
  path?: never;
  query?: never;
  url: "/apis/v1/auth/reset-password";
};

export type ResetPasswordApisV1AuthResetPasswordPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ResetPasswordApisV1AuthResetPasswordPostError =
  ResetPasswordApisV1AuthResetPasswordPostErrors[keyof ResetPasswordApisV1AuthResetPasswordPostErrors];

export type ResetPasswordApisV1AuthResetPasswordPostResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type ResetPasswordApisV1AuthResetPasswordPostResponse =
  ResetPasswordApisV1AuthResetPasswordPostResponses[keyof ResetPasswordApisV1AuthResetPasswordPostResponses];

export type RefreshTokenApisV1AuthRefreshPostData = {
  body?: never;
  path?: never;
  query?: never;
  url: "/apis/v1/auth/refresh";
};

export type RefreshTokenApisV1AuthRefreshPostResponses = {
  /**
   * Successful Response
   */
  200: LoginResponse;
};

export type RefreshTokenApisV1AuthRefreshPostResponse =
  RefreshTokenApisV1AuthRefreshPostResponses[keyof RefreshTokenApisV1AuthRefreshPostResponses];

export type ImageUploadApisV1ImgBedPostData = {
  body: BodyImageUploadApisV1ImgBedPost;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/img_bed/";
};

export type ImageUploadApisV1ImgBedPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImageUploadApisV1ImgBedPostError =
  ImageUploadApisV1ImgBedPostErrors[keyof ImageUploadApisV1ImgBedPostErrors];

export type ImageUploadApisV1ImgBedPostResponses = {
  /**
   * Successful Response
   */
  200: ImageUploadResponse;
};

export type ImageUploadApisV1ImgBedPostResponse =
  ImageUploadApisV1ImgBedPostResponses[keyof ImageUploadApisV1ImgBedPostResponses];

export type ImageGetApisV1ImgBedObjectNameGetData = {
  body?: never;
  path: {
    /**
     * Object Name
     */
    object_name: string;
  };
  query?: never;
  url: "/apis/v1/img_bed/{object_name}";
};

export type ImageGetApisV1ImgBedObjectNameGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ImageGetApisV1ImgBedObjectNameGetError =
  ImageGetApisV1ImgBedObjectNameGetErrors[keyof ImageGetApisV1ImgBedObjectNameGetErrors];

export type ImageGetApisV1ImgBedObjectNameGetResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetPermissionApisV1PermissionGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/permission/";
};

export type GetPermissionApisV1PermissionGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetPermissionApisV1PermissionGetError =
  GetPermissionApisV1PermissionGetErrors[keyof GetPermissionApisV1PermissionGetErrors];

export type GetPermissionApisV1PermissionGetResponses = {
  /**
   * Successful Response
   */
  200: PermissionsResponse;
};

export type GetPermissionApisV1PermissionGetResponse =
  GetPermissionApisV1PermissionGetResponses[keyof GetPermissionApisV1PermissionGetResponses];

export type HavePermissionApisV1PermissionPostData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query: {
    /**
     * Permission Code
     */
    permission_code: string;
  };
  url: "/apis/v1/permission/";
};

export type HavePermissionApisV1PermissionPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type HavePermissionApisV1PermissionPostError =
  HavePermissionApisV1PermissionPostErrors[keyof HavePermissionApisV1PermissionPostErrors];

export type HavePermissionApisV1PermissionPostResponses = {
  /**
   * Response Have Permission Apis V1 Permission  Post
   *
   * Successful Response
   */
  200: boolean;
};

export type HavePermissionApisV1PermissionPostResponse =
  HavePermissionApisV1PermissionPostResponses[keyof HavePermissionApisV1PermissionPostResponses];

export type GetUserInfoApisV1UserInfoGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/user/info";
};

export type GetUserInfoApisV1UserInfoGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserInfoApisV1UserInfoGetError =
  GetUserInfoApisV1UserInfoGetErrors[keyof GetUserInfoApisV1UserInfoGetErrors];

export type GetUserInfoApisV1UserInfoGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetUserInfoApisV1UserInfoGetResponse =
  GetUserInfoApisV1UserInfoGetResponses[keyof GetUserInfoApisV1UserInfoGetResponses];

export type GetUserInfoByIdApisV1UserInfoUserUuidGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * User Uuid
     */
    user_uuid: string;
  };
  query?: never;
  url: "/apis/v1/user/info/{user_uuid}";
};

export type GetUserInfoByIdApisV1UserInfoUserUuidGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUserInfoByIdApisV1UserInfoUserUuidGetError =
  GetUserInfoByIdApisV1UserInfoUserUuidGetErrors[keyof GetUserInfoByIdApisV1UserInfoUserUuidGetErrors];

export type GetUserInfoByIdApisV1UserInfoUserUuidGetResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type GetUserInfoByIdApisV1UserInfoUserUuidGetResponse =
  GetUserInfoByIdApisV1UserInfoUserUuidGetResponses[keyof GetUserInfoByIdApisV1UserInfoUserUuidGetResponses];

export type EditUserInfoApisV1UserEditPostData = {
  body: UserEdit;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/user/edit";
};

export type EditUserInfoApisV1UserEditPostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type EditUserInfoApisV1UserEditPostError =
  EditUserInfoApisV1UserEditPostErrors[keyof EditUserInfoApisV1UserEditPostErrors];

export type EditUserInfoApisV1UserEditPostResponses = {
  /**
   * Successful Response
   */
  200: UserResponse;
};

export type EditUserInfoApisV1UserEditPostResponse =
  EditUserInfoApisV1UserEditPostResponses[keyof EditUserInfoApisV1UserEditPostResponses];

export type CreateCommentApisV1CommentCreatePostData = {
  body: CommentCreate;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/comment/create";
};

export type CreateCommentApisV1CommentCreatePostErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type CreateCommentApisV1CommentCreatePostError =
  CreateCommentApisV1CommentCreatePostErrors[keyof CreateCommentApisV1CommentCreatePostErrors];

export type CreateCommentApisV1CommentCreatePostResponses = {
  /**
   * Successful Response
   */
  200: Comment;
};

export type CreateCommentApisV1CommentCreatePostResponse =
  CreateCommentApisV1CommentCreatePostResponses[keyof CreateCommentApisV1CommentCreatePostResponses];

export type GetCommentsApisV1CommentGetBlogIdGetData = {
  body?: never;
  path: {
    /**
     * Blog Id
     */
    blog_id: number;
  };
  query?: never;
  url: "/apis/v1/comment/get/{blog_id}";
};

export type GetCommentsApisV1CommentGetBlogIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCommentsApisV1CommentGetBlogIdGetError =
  GetCommentsApisV1CommentGetBlogIdGetErrors[keyof GetCommentsApisV1CommentGetBlogIdGetErrors];

export type GetCommentsApisV1CommentGetBlogIdGetResponses = {
  /**
   * Successful Response
   */
  200: CommentsResponse;
};

export type GetCommentsApisV1CommentGetBlogIdGetResponse =
  GetCommentsApisV1CommentGetBlogIdGetResponses[keyof GetCommentsApisV1CommentGetBlogIdGetResponses];

export type GetCommentApisV1CommentGetCommentIdGetData = {
  body?: never;
  path: {
    /**
     * Comment Id
     */
    comment_id: number;
  };
  query?: never;
  url: "/apis/v1/comment/get/{comment_id}";
};

export type GetCommentApisV1CommentGetCommentIdGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCommentApisV1CommentGetCommentIdGetError =
  GetCommentApisV1CommentGetCommentIdGetErrors[keyof GetCommentApisV1CommentGetCommentIdGetErrors];

export type GetCommentApisV1CommentGetCommentIdGetResponses = {
  /**
   * Successful Response
   */
  200: Comment;
};

export type GetCommentApisV1CommentGetCommentIdGetResponse =
  GetCommentApisV1CommentGetCommentIdGetResponses[keyof GetCommentApisV1CommentGetCommentIdGetResponses];

export type DeleteCommentApisV1CommentDeleteCommentIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Comment Id
     */
    comment_id: number;
  };
  query?: never;
  url: "/apis/v1/comment/delete/{comment_id}";
};

export type DeleteCommentApisV1CommentDeleteCommentIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCommentApisV1CommentDeleteCommentIdDeleteError =
  DeleteCommentApisV1CommentDeleteCommentIdDeleteErrors[keyof DeleteCommentApisV1CommentDeleteCommentIdDeleteErrors];

export type DeleteCommentApisV1CommentDeleteCommentIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: MessageResponse;
};

export type DeleteCommentApisV1CommentDeleteCommentIdDeleteResponse =
  DeleteCommentApisV1CommentDeleteCommentIdDeleteResponses[keyof DeleteCommentApisV1CommentDeleteCommentIdDeleteResponses];

export type UpdateCommentApisV1CommentUpdateCommentIdPutData = {
  body: CommentCreate;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Comment Id
     */
    comment_id: number;
  };
  query?: never;
  url: "/apis/v1/comment/update/{comment_id}";
};

export type UpdateCommentApisV1CommentUpdateCommentIdPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateCommentApisV1CommentUpdateCommentIdPutError =
  UpdateCommentApisV1CommentUpdateCommentIdPutErrors[keyof UpdateCommentApisV1CommentUpdateCommentIdPutErrors];

export type UpdateCommentApisV1CommentUpdateCommentIdPutResponses = {
  /**
   * Successful Response
   */
  200: Comment;
};

export type UpdateCommentApisV1CommentUpdateCommentIdPutResponse =
  UpdateCommentApisV1CommentUpdateCommentIdPutResponses[keyof UpdateCommentApisV1CommentUpdateCommentIdPutResponses];

export type GetStatsApisV1AdminStatsGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/admin/stats";
};

export type GetStatsApisV1AdminStatsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetStatsApisV1AdminStatsGetError =
  GetStatsApisV1AdminStatsGetErrors[keyof GetStatsApisV1AdminStatsGetErrors];

export type GetStatsApisV1AdminStatsGetResponses = {
  /**
   * Successful Response
   */
  200: AdminStatsResponse;
};

export type GetStatsApisV1AdminStatsGetResponse =
  GetStatsApisV1AdminStatsGetResponses[keyof GetStatsApisV1AdminStatsGetResponses];

export type GetUsersApisV1AdminUsersGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
  };
  url: "/apis/v1/admin/users";
};

export type GetUsersApisV1AdminUsersGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetUsersApisV1AdminUsersGetError =
  GetUsersApisV1AdminUsersGetErrors[keyof GetUsersApisV1AdminUsersGetErrors];

export type GetUsersApisV1AdminUsersGetResponses = {
  /**
   * Successful Response
   */
  200: AdminUserListResponse;
};

export type GetUsersApisV1AdminUsersGetResponse =
  GetUsersApisV1AdminUsersGetResponses[keyof GetUsersApisV1AdminUsersGetResponses];

export type UpdateUserRolesApisV1AdminUsersUserIdRolePutData = {
  body: UpdateUserRoleRequest;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/apis/v1/admin/users/{user_id}/role";
};

export type UpdateUserRolesApisV1AdminUsersUserIdRolePutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type UpdateUserRolesApisV1AdminUsersUserIdRolePutError =
  UpdateUserRolesApisV1AdminUsersUserIdRolePutErrors[keyof UpdateUserRolesApisV1AdminUsersUserIdRolePutErrors];

export type UpdateUserRolesApisV1AdminUsersUserIdRolePutResponses = {
  /**
   * Successful Response
   */
  200: AdminUserResponse;
};

export type UpdateUserRolesApisV1AdminUsersUserIdRolePutResponse =
  UpdateUserRolesApisV1AdminUsersUserIdRolePutResponses[keyof UpdateUserRolesApisV1AdminUsersUserIdRolePutResponses];

export type DeleteUserApisV1AdminUsersUserIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * User Id
     */
    user_id: number;
  };
  query?: never;
  url: "/apis/v1/admin/users/{user_id}";
};

export type DeleteUserApisV1AdminUsersUserIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteUserApisV1AdminUsersUserIdDeleteError =
  DeleteUserApisV1AdminUsersUserIdDeleteErrors[keyof DeleteUserApisV1AdminUsersUserIdDeleteErrors];

export type DeleteUserApisV1AdminUsersUserIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetBlogsApisV1AdminBlogsGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
    /**
     * Published
     */
    published?: boolean | null;
  };
  url: "/apis/v1/admin/blogs";
};

export type GetBlogsApisV1AdminBlogsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetBlogsApisV1AdminBlogsGetError =
  GetBlogsApisV1AdminBlogsGetErrors[keyof GetBlogsApisV1AdminBlogsGetErrors];

export type GetBlogsApisV1AdminBlogsGetResponses = {
  /**
   * Successful Response
   */
  200: AdminBlogListResponse;
};

export type GetBlogsApisV1AdminBlogsGetResponse =
  GetBlogsApisV1AdminBlogsGetResponses[keyof GetBlogsApisV1AdminBlogsGetResponses];

export type ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Blog Id
     */
    blog_id: number;
  };
  query?: never;
  url: "/apis/v1/admin/blogs/{blog_id}/publish";
};

export type ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutError =
  ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutErrors[keyof ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutErrors];

export type ToggleBlogPublishApisV1AdminBlogsBlogIdPublishPutResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type DeleteBlogApisV1AdminBlogsBlogIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Blog Id
     */
    blog_id: number;
  };
  query?: never;
  url: "/apis/v1/admin/blogs/{blog_id}";
};

export type DeleteBlogApisV1AdminBlogsBlogIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteBlogApisV1AdminBlogsBlogIdDeleteError =
  DeleteBlogApisV1AdminBlogsBlogIdDeleteErrors[keyof DeleteBlogApisV1AdminBlogsBlogIdDeleteErrors];

export type DeleteBlogApisV1AdminBlogsBlogIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetCommentsApisV1AdminCommentsGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: {
    /**
     * Page
     */
    page?: number;
    /**
     * Page Size
     */
    page_size?: number;
  };
  url: "/apis/v1/admin/comments";
};

export type GetCommentsApisV1AdminCommentsGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetCommentsApisV1AdminCommentsGetError =
  GetCommentsApisV1AdminCommentsGetErrors[keyof GetCommentsApisV1AdminCommentsGetErrors];

export type GetCommentsApisV1AdminCommentsGetResponses = {
  /**
   * Successful Response
   */
  200: AdminCommentListResponse;
};

export type GetCommentsApisV1AdminCommentsGetResponse =
  GetCommentsApisV1AdminCommentsGetResponses[keyof GetCommentsApisV1AdminCommentsGetResponses];

export type DeleteCommentApisV1AdminCommentsCommentIdDeleteData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path: {
    /**
     * Comment Id
     */
    comment_id: number;
  };
  query?: never;
  url: "/apis/v1/admin/comments/{comment_id}";
};

export type DeleteCommentApisV1AdminCommentsCommentIdDeleteErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type DeleteCommentApisV1AdminCommentsCommentIdDeleteError =
  DeleteCommentApisV1AdminCommentsCommentIdDeleteErrors[keyof DeleteCommentApisV1AdminCommentsCommentIdDeleteErrors];

export type DeleteCommentApisV1AdminCommentsCommentIdDeleteResponses = {
  /**
   * Successful Response
   */
  200: unknown;
};

export type GetRolesApisV1AdminRolesGetData = {
  body?: never;
  headers?: {
    /**
     * Authorization
     */
    Authorization?: string | null;
  };
  path?: never;
  query?: never;
  url: "/apis/v1/admin/roles";
};

export type GetRolesApisV1AdminRolesGetErrors = {
  /**
   * Validation Error
   */
  422: HttpValidationError;
};

export type GetRolesApisV1AdminRolesGetError =
  GetRolesApisV1AdminRolesGetErrors[keyof GetRolesApisV1AdminRolesGetErrors];

export type GetRolesApisV1AdminRolesGetResponses = {
  /**
   * Response Get Roles Apis V1 Admin Roles Get
   *
   * Successful Response
   */
  200: Array<AdminRoleResponse>;
};

export type GetRolesApisV1AdminRolesGetResponse =
  GetRolesApisV1AdminRolesGetResponses[keyof GetRolesApisV1AdminRolesGetResponses];
