"""init

Revision ID: 0da686ff5fbd
Revises: 
Create Date: 2025-04-26 19:55:22.954275

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '0da686ff5fbd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
