"""fix link user follows

Revision ID: 16d560dd93d3
Revises: e666b2d0e443
Create Date: 2025-05-02 15:16:20.246161

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '16d560dd93d3'
down_revision: Union[str, None] = 'e666b2d0e443'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
