"""fix user follows

Revision ID: 4e1540346460
Revises: 16d560dd93d3
Create Date: 2025-05-02 15:30:55.198333

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '4e1540346460'
down_revision: Union[str, None] = '16d560dd93d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
