"""init

Revision ID: 6ac087767374
Revises: 
Create Date: 2025-04-27 22:07:37.464532

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = '6ac087767374'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
