"""fix user follows

Revision ID: c29d430fab68
Revises: 4e1540346460
Create Date: 2025-05-02 15:32:32.337502

"""
from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = 'c29d430fab68'
down_revision: Union[str, None] = '4e1540346460'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
