"""fix link table

Revision ID: ed285cf70138
Revises: c4f7475cd89e
Create Date: 2025-04-30 19:42:17.387946

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'ed285cf70138'
down_revision: Union[str, None] = 'c4f7475cd89e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_user_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_user_info',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('user_info_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_info_id'], ['user_info.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'user_info_id')
    )
    # ### end Alembic commands ###
